#!/bin/bash

echo "hash;date;added;deleted;filename;user"
git log --pretty=tformat:'%aI %H %an' | while read date hash name; do
	git log -n 1 --pretty=tformat: --numstat $hash | while read added deleted filename; do
		echo "${hash};${date};${added};${deleted};${filename};${name}"
	done
done

